### ISSUE TITLE
Don't merge until checks complete

### ISSUE THREAD

**Issue by AArnott** [squalrus/merge-bot#15]
**Is your feature request related to a problem? Please describe.**

From the docs it's not clear that the merge-bot will wait till PR checks all pass prior to merging. It talks about reviewers, labels, etc., but not the PR checks. 

**Describe the solution you'd like**

I'd like this merge bot to wait for checks to all pass prior to merging.

**Describe alternatives you've considered**

Writing my own github action. 😛

**Comment by squalrus** [comment]
Yes! This is great! Are you aware if this check is available through the API?

**Comment by AArnott** [comment]
It is. And there are trigger events that can tell you when a check status has changed so you can re-evaluate whether to complete the PR.

**Comment by squalrus** [comment]
Awesome! I am open to contributions (or collaborating) if you're interested. Either way I'll look more into this over the weekend. Thanks for the issue!

**Comment by squalrus** [comment]
Thanks again for raising this -- I have wanted to add this for a while.

After doing some research on the Checks API, I was able to implement this feature: https://github.com/squalrus/merge-bot/pull/20

I had to account for the check running for merge-bot evaluating the other checks. With that said, the logic looks for completed and succeeded checks that are one less than the total of the suite (omitting the merge-bot check).

Also, as for triggering merge-bot on the completion of a check suite, this is apparently not as simple as listening to [`check_run`](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#check-run-event-check_run) or [`check_suite`](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#check-suite-event-check_suite) events, they are not triggered. According to [a forum post](https://github.community/t5/GitHub-Actions/on-check-suite-never-gets-called/td-p/38955) this is to prevent "a circular workflow execution". Instead I am going to experiment listening on the [`status`](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#status-event-status) event.

**Comment by squalrus** [comment]
This is satisfied in that the pull request will not merge if the checks aren't complete, however I'd like to figure out how to re-trigger the Action when the checks are complete: https://github.com/squalrus/merge-bot/issues/22
