### ISSUE TITLE
Remove `node_modules`

### ISSUE THREAD

**Issue by nbrugger-tgm** [squalrus/merge-bot#65]
Its a very bad practice to upload the `node_modules` folder to github. You have the complete source-code of hundreds dependencies in your repo.

**Comment by squalrus** [comment]
AFAIK this is still a requirement for publishing a JavaScript GitHub Action: https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github

It looks like there may be an alternative, a tool called `@vercel/ncc` to compile your code and modules into one file used for distribution, but I haven't experienced any issues with the current approach.

**Comment by nbrugger-tgm** [comment]
Yes, it might not be a solution but next time use the github js template (`https://github.com/actions/javascript-action`) or https://github.com/actions/typescript-action

But you can use any packager like "webpack" or "babel" that compiles (just used code) into one file
